# Generated by Django 3.2 on 2024-03-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epid', models.CharField(max_length=10)),
                ('ename', models.CharField(max_length=50)),
                ('esal', models.IntegerField(default=15000)),
                ('edesg', models.CharField(max_length=50)),
            ],
        ),
    ]
