# Generated by Django 3.2 on 2024-03-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DemoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='edesg',
            field=models.CharField(choices=[('0', 'Select Your Designation'), ('1', 'Junior Trainee'), ('2', 'Senior Trainer'), ('3', 'Intern')], default='0', max_length=10),
        ),
    ]
